---
abstract: 'timezones from the Olson database'
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  Module::Build: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0
  perl: 5.006
  strict: 0
  warnings: 0
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-TimeZone-Olson
provides:
  DateTime::TimeZone::Olson:
    file: lib/DateTime/TimeZone/Olson.pm
    version: 0.000
requires:
  DateTime::TimeZone::Tzfile: 0.004
  Time::OlsonTZ::Data: 0.201012
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.000
